# ======================================================================================================================
# FeatherSleep Plugin Configuration                                                      Written by: Zerek / zerek.dev
# ======================================================================================================================

Sleeping-calculation-settings:
  # Which players should be excluded from the totla player count when calculating the percentage of sleeping players.
  ignore-afk: true # Uses EssentialsX AFK status
  ignore-vanished: true # Uses a metadata check on players that most vanish plugins comply with.
  ignore-bypass: true # feather.sleep.bypass

clear-weather-on-wake: true

wakeup-message: "<gold>Good Morning"
